// export const products = [
//   {
//     id: 1,
//     category: "budget",
//     name: "Product 1",
//     price: 10.99,
//     description: "This is the description for Product 1.",
//   },
//   {
//     id: 2,
//     category: "budget",
//     name: "Product 2",
//     price: 19.99,
//     description: "This is the description for Product 2.",
//   },
//   {
//     " id": 3,
//     category: "budget",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 3.",
//   },
//   {
//     " id": 4,
//     category: "special",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 4.",
//   },
//   {
//     " id": 5,
//     category: "special",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 5.",
//   },
//   {
//     " id": 6,
//     category: "special",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 6.",
//   },
//   {
//     " id": 7,
//     category: "special",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 7.",
//   },
//   {
//     " id": 8,
//     category: "children",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 8.",
//   },
//   {
//     " id": 9,
//     category: "children",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 9.",
//   },
//   {
//     " id": 10,
//     category: "children",
//     name: "Product 3",
//     price: 7.5,
//     description: "This is the description for Product 10.",
//   },
// ];